import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# Channel Phase — drives TOPSIS weights, title format, CTA strategy
# GROWTH  : Pre-YPP (<1000 subs or <4000 watch hrs) → optimise for watch time
# REVENUE : Full YPP unlocked → optimise for RPM × Views × MidRoll
# SCALE   : 10K+ subs → optimise for RPM + brand deals + affiliates
# ─────────────────────────────────────────────────────────────────────────────
CHANNEL_PHASE_GROWTH  = "GROWTH"
CHANNEL_PHASE_REVENUE = "REVENUE"
CHANNEL_PHASE_SCALE   = "SCALE"

# YPP thresholds (YouTube Partner Program 2026)
YPP_SUBS_THRESHOLD        = 1_000
YPP_WATCH_HOURS_THRESHOLD = 4_000
YPP_SCALE_SUBS_THRESHOLD  = 10_000


class SEOMetadata(BaseModel):
    """YouTube SEO metadata generated by StoryDesigner alongside the script."""
    title: str = ""                          # ≤70 chars, CTR-optimised with year/number
    description: str = ""                    # 800+ chars: hook + chapters + sources + disclaimer
    tags: List[str] = Field(default_factory=list)     # 15 high-volume YouTube search tags
    thumbnail_brief: str = ""               # ≤6 words for thumbnail text overlay
    chapter_timestamps: List[str] = Field(default_factory=list)  # ["0:00 Intro", "1:20 ..." ...]


class RevenueForecast(BaseModel):
    """Monetisation yield forecast computed by MonetizationYieldOptimizer."""
    predicted_views: float = 0.0
    estimated_rpm_usd: float = 0.0
    midroll_multiplier: float = 0.0
    base_ad_revenue_usd: float = 0.0
    total_expected_revenue_usd: float = 0.0
    audience_type: str = ""    # "investor" | "tech" | "health" | "business" | "blocked"
    niche_category: str = ""


class VerifiedFact(BaseModel):
    source_id: str
    headline: str
    summary: str
    url: str
    source_name: str = Field(
        default="Verified Reports",
        description="Trusted organization/publisher name e.g. 'TechCrunch', 'Reuters'"
    )
    timestamp: Optional[str] = None


class TopicCandidate(BaseModel):
    candidate_id: str
    headline: str
    summary: str
    source_url: str
    keywords: List[str]
    tvs_score: float = Field(..., description="Exponential Moving Average Trend Velocity Score")
    rpm_score: float = Field(..., description="Advertiser CPM Cosine Similarity Score")
    idi_score: float = Field(..., description="Semantic Novelty / Information Density Index")
    sdi_score: float = Field(..., description="Sentiment Disruption & Controversy Index")
    shm_score: float = Field(default=1.0, description="Social Media Hype Multiplier (X/Twitter/Reddit)")
    vph_score: float = Field(default=1.0, description="YouTube Competitor Views-per-Hour Velocity")
    sat_score: float = Field(..., description="Market Saturation Penalty")
    topsis_score: Optional[float] = Field(None, description="TOPSIS Relative Closeness Score (C_i*)")
    # Phase-aware audience classification added by RSS ingestion layer
    audience_type: str = Field(default="general", description="investor|tech|health|business|blocked")
    niche_category: str = Field(default="Technology & Artificial Intelligence", description="High-RPM niche label")


from enum import Enum

class VisualType(str, Enum):
    STANDARD_IMAGE = "standard_image"      # Flux.1 image with Ken Burns pan
    GIF_MEME = "gif_meme"                  # Reaction meme search from GIPHY/Tenor
    MATPLOTLIB_CHART = "matplotlib_chart"  # Dynamic dark-mode line/bar chart
    SVG_TICKER = "svg_ticker"              # Glowing stock ticker/counter

class ShotData(BaseModel):
    shot_id: int
    act_index: int = Field(..., ge=1, le=6, description="Act 1 to 6 in 6-Act dramatic model")
    narration_text: str = Field(..., description="Narration text (max 20 words per sub-chunk)")
    visual_prompt: str = Field(..., description="16:9 cinematic visual prompt")
    visual_type: VisualType = Field(default=VisualType.STANDARD_IMAGE, description="Visual format type to generate")
    duration_estimate: float = Field(default=5.0, description="Estimated duration in seconds")


class ScriptData(BaseModel):
    title: str
    target_shots: int
    shots: List[ShotData]
    estimated_runtime_seconds: float = 0.0


class AssetPaths(BaseModel):
    audio: Dict[str, str] = Field(default_factory=dict, description="Map of shot_id -> wav path")
    subtitles: Dict[str, str] = Field(default_factory=dict, description="Map of shot_id -> ass path")
    visuals: Dict[str, str] = Field(default_factory=dict, description="Map of shot_id -> mp4 path")
    final_video: Optional[str] = None
    thumbnail: Optional[str] = None          # 1280x720 YouTube thumbnail PNG
    shorts_clip: Optional[str] = None        # 1080x1920 vertical 60-90s Shorts clip


class UploadMetadata(BaseModel):
    video_id: Optional[str] = None
    shorts_video_id: Optional[str] = None
    status: str = "PENDING"
    retry_count: int = 0
    synthetic_content_flag: bool = True
    extra_metadata: Optional[Dict[str, Any]] = None


class ChannelStats(BaseModel):
    """Persisted channel growth metrics — read from YouTube Analytics API daily."""
    subscribers: int = 0
    total_watch_hours: int = 0
    channel_phase: str = CHANNEL_PHASE_GROWTH  # GROWTH | REVENUE | SCALE
    last_updated: str = ""
    ypp_unlocked: bool = False


class GlobalState(BaseModel):
    pipeline_id: str
    timestamp: str
    execution_stage: str = "INITIALIZATION"
    selected_topic: Optional[TopicCandidate] = None
    verified_facts: List[VerifiedFact] = Field(default_factory=list)
    script_data: Optional[ScriptData] = None
    asset_paths: AssetPaths = Field(default_factory=AssetPaths)
    upload_metadata: UploadMetadata = Field(default_factory=UploadMetadata)
    # Phase-aware monetisation fields
    seo_metadata: Optional[SEOMetadata] = None
    revenue_forecast: Optional[RevenueForecast] = None
    channel_stats: ChannelStats = Field(default_factory=ChannelStats)

    @property
    def channel_phase(self) -> str:
        return self.channel_stats.channel_phase

    @property
    def is_monetised(self) -> bool:
        return self.channel_stats.ypp_unlocked

    @property
    def current_year(self) -> str:
        return str(datetime.datetime.now(datetime.timezone.utc).year)

    @property
    def current_date_str(self) -> str:
        return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")

    @property
    def current_month_year(self) -> str:
        return datetime.datetime.now(datetime.timezone.utc).strftime("%B %Y")
