import uuid
import os
import json
import datetime
from typing import Dict, Any, Optional
from src.schemas.state import GlobalState, UploadMetadata
from src.schemas.a2a import A2AMessage, AgentRole, AgentIntent, compute_state_hash
from mcp_servers.youtube_cloud.server import (
    check_quota_available,
    upload_youtube_resumable,
    upload_short,
    insert_pinned_comment,
    QuotaCheckRequest,
    UploadRequest,
    InsertCommentRequest,
)
from src.engine.run_budget import run_budget


# Fake video identifiers that must NEVER be treated as a successful publish.
# A `demo_*`/sentinel id means the upload silently fell back to the mock path
# (token failure, 403, quota, network) — recording it as PUBLISHED_SUCCESS masks
# a real outage and poisons topic dedup (see publish-integrity-quality-fix-plan.md
# issue #1). Reject them everywhere: publish, resume guard, and side effects.
def _is_real_video_id(video_id: Optional[str]) -> bool:
    if not video_id:
        return False
    vid = str(video_id).strip()
    if not vid or len(vid) > 64:
        return False
    return vid.lower() not in ("demo_id", "uploaded_demo_id") and not vid.lower().startswith("demo_")


class PublisherAgent:
    """
    Publisher Agent managing YouTube MCP upload tools, checking daily API quotas,
    injecting synthetic content metadata tags, and updating GlobalState.
    """

    def __init__(self, name: str = "Publisher"):
        self.name = name

    def _trigger_pi_warmup(self, title: str, state: GlobalState) -> bool:
        """SSH to the Pi edge node and run the no-link Reddit warmup for the
        just-published video, fire-and-forget so publish never blocks. Reads Pi
        connection config from env (mirrors sync_to_pi.sh defaults). Enabled by
        default; set REDDIT_PI_WARMUP_ON_PUBLISH=0 to disable. Non-fatal."""
        import subprocess
        if os.getenv("REDDIT_PI_WARMUP_ON_PUBLISH", "1").strip().lower() in ("0", "false", "no"):
            return False
        pi_host = os.getenv("PI5_IP", "100.108.116.100")
        pi_user = os.getenv("PI5_USER", "jeevanjoshi")
        pi_dir = os.getenv("PI5_TARGET_DIR", "/home/jeevanjoshi/buzzdropfeedv2")
        count = int(os.getenv("REDDIT_WARMUP_COUNT", "3"))
        title_json = json.dumps(title).replace('"', '\\"')
        py = (
            f"cd {pi_dir} && source venv/bin/activate && "
            f"python reddit_warmup.py --count {count}"
        )
        if title:
            py += f' --title "{title_json}"'
        cmd = ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=20",
               f"{pi_user}@{pi_host}", py]
        try:
            devnull = open(os.devnull, "w")
            import threading
            def _run():
                try:
                    subprocess.run(cmd, stdout=devnull, stderr=devnull, timeout=600)
                except Exception as e:
                    print(f"[PiWarmup] background trigger failed: {e}")
                finally:
                    devnull.close()
            threading.Thread(target=_run, daemon=True).start()
            print("[PiWarmup] launched on the Pi in background (fire-and-forget).")
            return True
        except Exception as e:
            print(f"[PiWarmup] trigger setup failed: {e}")
            return False

    async def publish_video(self, state: GlobalState, daily_uploads: int = 0) -> UploadMetadata:
        """
        Interfaces with YouTube Publishing MCP Server to check quota and upload video.
        """
        if not state.asset_paths.final_video:
            raise ValueError("Publishing failed: state.asset_paths.final_video is None")

        # 1. Quota Check
        quota_res = await check_quota_available(QuotaCheckRequest(current_daily_uploads=daily_uploads))
        if not quota_res["is_safe"]:
            raise RuntimeError(f"YouTube daily API quota limit reached ({quota_res['used_units']} / {quota_res['quota_limit']} units used)")
        run_budget.record_yt("channels")

        # 2. Upload Video — prefer the rich SEO metadata (high-CTR title, full
        #    description, tags) generated by StoryDesigner when available.
        seo = state.seo_metadata
        if seo:
            title = seo.title
            desc = seo.description
            tags = seo.tags or []
        else:
            title = state.script_data.title if state.script_data else state.selected_topic.headline
            default_chapters_str = (
                "0:00 - Act 1: The Inciting Incident\n"
                "2:15 - Act 2: Historical Precedents & Origins\n"
                "4:30 - Act 3: Deep Technical Mechanics\n"
                "6:45 - Act 4: Actionable Real-World Impact\n"
                "9:00 - Act 5: Critical Risks & Counter-Arguments\n"
                "11:15 - Act 6: Strategic Future Verdict"
            )
            desc = (
                f"Deep-dive financial storytelling breakdown on: {title}.\n\n"
                f"CHAPTERS:\n"
                f"{default_chapters_str}\n\n"
                f"Sources & Facts: {state.selected_topic.source_url if state.selected_topic else 'Verified Financial News Feeds'}\n\n"
                f"Disclaimer: AI-synthesized visualization for educational & infotainment storytelling."
            )
            tags = state.selected_topic.keywords if state.selected_topic else ["finance", "tech"]

        # Calculate actual start times for each act from the shared helper.
        # Uses MEASURED shot durations when present (publish time), falling back
        # to duration_estimate; same definition as story_designer design time.
        # Reuse the content-aware act titles the designer already produced so the
        # publish-time block is timestamps-only, not renamed back to the generic
        # static labels.
        from src.engine.chapters import compute_act_chapters, derive_contextual_act_titles
        shots = state.script_data.shots if state.script_data else None
        durs = state.asset_paths.measured_durations if state.asset_paths else None
        crossfade = getattr(state.asset_paths, "crossfade_used", 0.0) if state.asset_paths else 0.0
        act_names = (seo.act_titles if seo and getattr(seo, "act_titles", None)
                     else derive_contextual_act_titles(shots))
        _ch_lines, chapter_timestamps = compute_act_chapters(
            shots=shots, measured_durations=durs, crossfade=crossfade,
            act_names=act_names,
        )
        chapters_str = "\n".join(_ch_lines)

        # Dynamic replacement of chapters in the description (kept for the
        # SEO-provided description; no regex drift because we generate the block
        # from the same helper, but tolerate the old static text too).
        old_chapters_pattern = (
            "0:00 - Act 1: The Inciting Incident\n"
            "2:15 - Act 2: Historical Precedents & Origins\n"
            "4:30 - Act 3: Deep Technical Mechanics\n"
            "6:45 - Act 4: Actionable Real-World Impact\n"
            "9:00 - Act 5: Critical Risks & Counter-Arguments\n"
            "11:15 - Act 6: Strategic Future Verdict"
        )
        if "[CHAPTERS_PLACEHOLDER]" in desc:
            desc = desc.replace("[CHAPTERS_PLACEHOLDER]", chapters_str)
        elif old_chapters_pattern in desc:
            desc = desc.replace(old_chapters_pattern, chapters_str)
        else:
            import re as _re
            # Replace whatever chapter block currently sits between "CHAPTERS:\n"
            # and the following blank line, using the freshly computed block.
            _desc, _n = _re.subn(
                r"CHAPTERS:\n.*?(?=\n\n|$)",
                lambda m: ("CHAPTERS:\n" + chapters_str),
                desc, count=1, flags=_re.DOTALL,
            )
            if _n:
                desc = _desc
            elif "CHAPTERS:" in desc:
                parts = desc.split("CHAPTERS:")
                desc = parts[0] + "CHAPTERS:\n" + chapters_str + "\n\n" + parts[1].split("\n\n", 1)[-1]
            else:
                desc += f"\n\nCHAPTERS:\n{chapters_str}"

        # Update the state object
        if seo:
            seo.description = desc
            seo.chapter_timestamps = chapter_timestamps

        # ── GROWTH-phase: drive subscribers + watch-time (pre-YPP) ──────────
        # Append a subscribe/bell + series-consistency line to the description
        # so discovery metadata actively converts viewers into subs (the YPP
        # requirement), instead of only optimising for ad RPM (post-YPP goal).
        phase = getattr(state, "channel_phase", "") or ""
        _GROWTH_DESC = (
            "\n\nNew here? Subscribe and hit the bell — we publish a new "
            "documentary every day. Drop your take in the comments!"
        )
        if phase == "GROWTH" and "subscribe" not in desc.lower():
            desc += _GROWTH_DESC
            if seo:
                seo.description = desc

        upload_res = await upload_youtube_resumable(UploadRequest(
            video_path=state.asset_paths.final_video,
            title=title,
            description=desc,
            tags=tags,
            thumbnail_path=state.asset_paths.thumbnail
        ))
        run_budget.record_yt("upload")

        # Abort on a fabricated/sentinel id BEFORE any side effect (pinned
        # comment, shorts, seed dispatch, dedup record). A demo id means the
        # upload fell back to mock and no video exists on YouTube — faking
        # PUBLISHED_SUCCESS here hides the outage and permanently marks the
        # topic as published.
        video_id = upload_res.get("video_id", "")
        if not _is_real_video_id(video_id):
            raise RuntimeError(
                f"YouTube upload did not produce a real video id (got: '{video_id}'). "
                f"Not publishing, not posting comments/seeds, not recording dedup. "
                f"Check the YouTube OAuth token/scopes (get_youtube_token.py)."
            )

        # 3. Post Instant Pinned Engagement Comment to kickstart early interaction metric.
        #    Non-fatal by design: comment insertion must never block a real publish.
        #    GROWTH phase pushes subscription + watch-time; later phases push comments.
        try:
            phase = getattr(state, "channel_phase", "") or ""
            if phase == "GROWTH":
                engagement_question = (
                    f"What did you think of {title}? Subscribe and hit the bell so you "
                    f"don't miss the next one — and tell us what to cover next below!"
                )
            else:
                engagement_question = (
                    f"What is your take on {title}? Share your thoughts below — we reply to every comment!"
                )
            res = await insert_pinned_comment(InsertCommentRequest(
                video_id=video_id,
                comment_text=engagement_question
            ))
            if res.get("status") != "success":
                print(f"[Publisher] Pinned comment skipped (status={res.get('status')}): {res.get('comment_id')}")
        except Exception as e:
            print(f"[Publisher] Pinned comment skipped (non-fatal): {e}")

        meta = UploadMetadata(
            video_id=video_id,
            status="PUBLISHED",
            retry_count=0,
            synthetic_content_flag=True
        )
        state.upload_metadata = meta
        state.execution_stage = "PUBLISHED_SUCCESS"

        # 4. Generate Short-Form 9:16 Micro-Content Clips (Shorts / Reels / TikTok)
        try:
            from src.engine.micro_content_producer import micro_content_producer
            short_paths = micro_content_producer.generate_shorts(state, max_shorts=2)
            if hasattr(state.asset_paths, "shorts"):
                state.asset_paths.shorts = short_paths
        except Exception as e:
            print(f"[MicroContentProducer] Notice: {e}")

        # 4b. GROWTH phase: PUBLISH the Shorts as YouTube Shorts (#1 discovery lever
        # for a pre-YPP channel — the master is monetized long-form, the clips feed
        # subscriptions + watch hours). Non-fatal; quota-shared with long-form.
        try:
            if (state.channel_phase == "GROWTH" and state.asset_paths.shorts):
                _short_title = (seo.title if seo and seo.title else title)[:90]
                _short_ids = []
                for _sp in state.asset_paths.shorts:
                    _res = await upload_short(UploadRequest(
                        video_path=_sp,
                        title=f"{_short_title} | Short",
                        description=desc[:4000],
                        tags=(tags or [])[:30] + ["#Shorts"],
                        category_id="22",
                    ))
                    if _res and _is_real_video_id(_res.get("video_id", "")):
                        _short_ids.append(_res["video_id"])
                        run_budget.record_yt("upload")
                if _short_ids:
                    meta.shorts_video_id = ",".join(_short_ids)
                    print(f"[Publisher] Published {len(_short_ids)} YouTube Short(s) for GROWTH discovery.")
        except Exception as e:
            print(f"[Publisher] Shorts upload skipped (non-fatal): {e}")


        # 5. Create & Dispatch Seed Traffic Package (Reddit / HN / Webhook)
        try:
            from src.engine.seed_distributor import seed_distributor
            youtube_url = f"https://www.youtube.com/watch?v={video_id}"
            seed_pkg = seed_distributor.create_seed_package(state, youtube_url)
            await seed_distributor.dispatch_webhook_notification(seed_pkg)
        except Exception as e:
            print(f"[SeedDistributor] Notice: {e}")

        # 5b. Active Thread Comment/Reply Seeding (Discussion Injection)
        try:
            from src.engine.active_thread_seeder import active_thread_seeder
            youtube_url = f"https://www.youtube.com/watch?v={video_id}"
            await active_thread_seeder.seed_active_discussions(state, youtube_url)
        except Exception as e:
            print(f"[ActiveThreadSeeder] Notice: {e}")

        # 5c. No-link warmup on the Pi (residential IP) to build Reddit account
        # trust. The main pipeline runs on OCI where Reddit is IP-blocked, so we
        # instruct the Pi edge node to run reddit_warmup.py for the published
        # video. Non-fatal: failures never affect the publish result.
        try:
            if _is_real_video_id(video_id):
                self._trigger_pi_warmup(title, state)
        except Exception as e:
            print(f"[PiWarmup] Notice: {e}")

        # Record to persistent deduplication history so future runs skip this topic
        from src.engine.topic_deduplicator import topic_deduplicator
        topic_headline = state.selected_topic.headline if state.selected_topic else title
        topic_summary = state.selected_topic.summary if state.selected_topic else ""
        topic_kws = state.selected_topic.keywords if state.selected_topic else []
        topic_deduplicator.record_published_topic(topic_headline, topic_summary, topic_kws)

        return meta


    async def process(self, state: GlobalState, daily_uploads: int = 0) -> A2AMessage:
        """
        Executes Publisher Agent workflow:
        1. Reads state.asset_paths.final_video
        2. Calls YouTube MCP server tools
        3. Updates state.upload_metadata
        4. Emits PUBLISHED_SUCCESS A2AMessage
        """
        meta = await self.publish_video(state, daily_uploads=daily_uploads)

        msg = A2AMessage(
            message_id=f"msg-{uuid.uuid4().hex[:8]}",
            sender=AgentRole.PUBLISHER,
            target=AgentRole.ORCHESTRATOR,
            intent=AgentIntent.PUBLISHED_SUCCESS,
            payload={
                "status": "SUCCESS",
                "video_id": meta.video_id,
                "youtube_url": f"https://www.youtube.com/watch?v={meta.video_id}",
                "synthetic_content": True
            },
            state_hash=compute_state_hash(state),
            timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat()
        )
        return msg
